# Generated by Django 6.0.6 on 2026-06-09 09:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)])),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('premium', 'Premium'), ('xl', 'XL (6+ seats)'), ('electric', 'Electric')], default='economy', max_length=20)),
                ('seats', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('registration_document', models.ImageField(blank=True, null=True, upload_to='vehicles/registration/')),
                ('insurance_document', models.ImageField(blank=True, null=True, upload_to='vehicles/insurance/')),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('dekra_status', models.CharField(choices=[('pending', 'Pending Verification'), ('in_progress', 'Verification In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Verification Expired')], default='pending', max_length=20)),
                ('dekra_verification_id', models.CharField(blank=True, max_length=100)),
                ('dekra_certificate_url', models.URLField(blank=True)),
                ('dekra_verified_at', models.DateTimeField(blank=True, null=True)),
                ('dekra_expires_at', models.DateField(blank=True, null=True)),
                ('dekra_rejection_reason', models.TextField(blank=True)),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('photo_back', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('photo_side', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('photo_interior', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('initial', 'Initial Inspection'), ('renewal', 'Renewal Inspection'), ('reinspection', 'Re-inspection (after failure)')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('dekra_request_id', models.CharField(max_length=100, unique=True)),
                ('dekra_inspection_id', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('inspection_location', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField(null=True)),
                ('inspection_report', models.JSONField(default=dict)),
                ('failure_reasons', models.JSONField(default=list)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_active'], name='vehicles_driver__60c40d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicles_license_b08e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['dekra_status'], name='vehicles_dekra_s_70a4d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('driver',), name='unique_primary_vehicle_per_driver'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['vehicle', 'status'], name='vehicle_ins_vehicle_277251_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['dekra_request_id'], name='vehicle_ins_dekra_r_607b16_idx'),
        ),
    ]
