# Generated by Django 6.0.6 on 2026-06-09 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50)),
                ('issuing_country', models.CharField(max_length=2)),
                ('issuing_state', models.CharField(blank=True, max_length=100)),
                ('license_classes', models.JSONField(default=list)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('front_image', models.ImageField(upload_to='licenses/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='licenses/back/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver_licenses',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_side', models.CharField(choices=[('front', 'Front'), ('back', 'Back')], max_length=10)),
                ('file', models.ImageField(upload_to='kyc/documents/')),
                ('provider_document_id', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_review', 'Awaiting Manual Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID Card'), ('residence_permit', 'Residence Permit')], max_length=20)),
                ('document_country', models.CharField(max_length=2)),
                ('provider', models.CharField(default='onfido', max_length=50)),
                ('provider_applicant_id', models.CharField(blank=True, max_length=100)),
                ('provider_check_id', models.CharField(blank=True, max_length=100)),
                ('result', models.JSONField(default=dict)),
                ('document_check_passed', models.BooleanField(null=True)),
                ('facial_similarity_passed', models.BooleanField(null=True)),
                ('liveness_check_passed', models.BooleanField(null=True)),
                ('rejection_reasons', models.JSONField(default=list)),
                ('document_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kyc_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
