# Generated by Django 6.0.6 on 2026-06-09 09:33

import django.contrib.gis.db.models.fields
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ride_type', models.CharField(choices=[('standard', 'Standard (Single Rider)'), ('shared', 'Shared Ride'), ('scheduled', 'Scheduled Ride')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching', 'Searching for Driver'), ('driver_assigned', 'Driver Assigned'), ('driver_arriving', 'Driver Arriving'), ('arrived', 'Driver Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address', models.TextField()),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('dropoff_address', models.TextField()),
                ('route_polyline', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('estimated_distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_type_requested', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('premium', 'Premium'), ('xl', 'XL')], default='economy', max_length=20)),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('rider_cancelled', 'Cancelled by Rider'), ('driver_cancelled', 'Cancelled by Driver'), ('no_drivers', 'No Drivers Available'), ('payment_failed', 'Payment Failed'), ('system', 'System Cancellation')], max_length=20)),
                ('cancellation_note', models.TextField(blank=True)),
                ('cancellation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'rides',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ride_locations',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RideParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('picked_up', 'Picked Up'), ('dropped_off', 'Dropped Off'), ('cancelled', 'Cancelled')], default='invited', max_length=20)),
                ('is_organizer', models.BooleanField(default=False)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address', models.TextField()),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('dropoff_address', models.TextField()),
                ('fare_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('fare_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_off_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ride_participants',
            },
        ),
    ]
