# Generated by Django 6.0.6 on 2026-06-09 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        ('rides', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='ridelocation',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='rideparticipant',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_participations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='rideparticipant',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='rideparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['rider', 'status'], name='rides_rider_i_6aa1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_driver__d736b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'requested_at'], name='rides_status_243aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['scheduled_pickup_time'], name='rides_schedul_31abd7_idx'),
        ),
        migrations.AddIndex(
            model_name='ridelocation',
            index=models.Index(fields=['ride', 'recorded_at'], name='ride_locati_ride_id_611316_idx'),
        ),
        migrations.AddIndex(
            model_name='rideparticipant',
            index=models.Index(fields=['ride', 'status'], name='ride_partic_ride_id_3cd2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='rideparticipant',
            index=models.Index(fields=['user', 'status'], name='ride_partic_user_id_e04894_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rideparticipant',
            unique_together={('ride', 'user')},
        ),
    ]
