# Generated by Django 5.2.15 on 2026-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('rider_cancelled', 'Cancelled by Rider'), ('driver_cancelled', 'Cancelled by Driver'), ('no_drivers', 'No Drivers Available'), ('payment_failed', 'Payment Failed'), ('system', 'System Cancellation')], max_length=225),
        ),
    ]
