# Generated by Django 5.2.15 on 2026-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='verification_code',
            field=models.CharField(blank=True, help_text='OTP/PIN to verify the ride with the driver', max_length=6, null=True),
        ),
    ]
