# Generated by Django 5.2.15 on 2026-06-17 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_ride_verification_code_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='ride',
            name='pool_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rideparticipant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideparticipant',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='rideparticipant',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('waiting_pickup', 'Waiting Pickup'), ('declined', 'Declined'), ('picked_up', 'Picked Up'), ('dropped_off', 'Dropped Off'), ('cancelled', 'Cancelled')], default='invited', max_length=20),
        ),
    ]
