# Generated by Django 5.2.15 on 2026-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ride_available_seats_ride_pool_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideparticipant',
            name='estimated_distance_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideparticipant',
            name='estimated_fare_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
