# Generated by Django 5.2.15 on 2026-06-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_rideparticipant_estimated_distance_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideparticipant',
            name='fare_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
