# Generated by Django 5.2.15 on 2026-06-18 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_rideparticipant_fare_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_type', models.CharField(choices=[('driver', 'Driver'), ('rider', 'Rider')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('audio_recording_vault', models.FileField(blank=True, null=True, upload_to='sos_evidence_audios/')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sos_alerts', to='rides.ride')),
            ],
            options={
                'db_table': 'emergency_sos_alerts',
            },
        ),
    ]
