# Generated by Django 5.2.15 on 2026-06-21 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_ridesharelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharelink',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ridesharelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridesharelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharelink',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
