# Generated by Django 5.2.15 on 2026-06-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_remove_ridesharelink_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharelink',
            name='expires_at',
        ),
    ]
