# Generated by Django 5.2.15 on 2026-06-21 15:07

import rides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_remove_ridesharelink_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharelink',
            name='expires_at',
            field=models.DateTimeField(default=rides.models.default_expiry),
        ),
    ]
