# Generated by Django 5.2.15 on 2026-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_alter_rideparticipant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideparticipant',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('searching', 'Searching for Driver'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('waiting_pickup', 'Waiting Pickup'), ('declined', 'Declined'), ('picked_up', 'Picked Up'), ('driver_assigned', 'Driver Assigned'), ('driver_arriving', 'Driver Arriving'), ('arrived', 'Driver Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='invited', max_length=20),
        ),
    ]
