# Generated by Django 6.0.6 on 2026-06-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_backfill_organizer_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideparticipant',
            name='seats_reserved',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
