# Generated by Django 5.2.15 on 2026-06-25 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_rideparticipant_seats_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSLocationPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='rides.emergencysos')),
            ],
            options={
                'db_table': 'sos_location_pings',
                'ordering': ['recorded_at'],
            },
        ),
    ]
