# Generated by Django 5.2.15 on 2026-06-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0020_soslocationping'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideparticipant',
            name='dropoff_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
