# Generated by Django 5.2.15 on 2026-07-15 19:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCity',
            fields=[
                ('city_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('geom_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Operational Cities',
            },
        ),
        migrations.CreateModel(
            name='ServiceableZone',
            fields=[
                ('zone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_label', models.CharField(max_length=150)),
                ('geom_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='serviceability.operationalcity')),
            ],
        ),
    ]
