# Generated by Django 6.0.6 on 2026-06-09 09:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rater_type', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver')], max_length=10)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('applies_to', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('both', 'Both')], max_length=10)),
                ('triggers_review', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Rating categories',
                'db_table': 'rating_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
