# Generated by Django 6.0.6 on 2026-06-09 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='rating',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='ratings.ratingcategory'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', 'created_at'], name='ratings_rated_u_89f35a_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['ride', 'rater_type'], name='ratings_ride_id_99f2d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('ride', 'rater')},
        ),
    ]
